baseURL = "https://sandbox-hugo-alpinejs.pages.dev/"
languageCode = "en-us"
title = "My New Hugo Site"

[module]
[[module.imports]]
path = 'github.com/spf13/hyde'
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-jslibs/alpinejs"
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-jslibs/turbolinks"