baseURL = "https://sandbox-hugo-turbo.pages.dev/"
languageCode = "en-us"
title = "Hugo with Turbo Drive"

[module]
[[module.imports]]
path = 'github.com/spf13/hyde'
[[module.imports]]
path = "github.com/meganii/hugo-mod-turbo"